version: "3"

dotenv: [".env"]

vars:
  NAME: homelab
  ENV: dev
  TF: terraform # tofu
  OUTPUT_DIR: "{{.USER_WORKING_DIR}}/output"
  SSH_DIR: "{{.OUTPUT_DIR}}/ssh"

includes:
  infra:
    taskfile: ./infra/Taskfile.yaml
    dir: ./infra

  apps:
    taskfile: ./apps/Taskfile.yaml
    dir: ./apps
