version: "3"

dotenv: [".env"]

vars:
  NAME: homelab
  ENV: dev
  TF: terraform # tofu
  OUTPUT_DIR: "{{.USER_WORKING_DIR}}/output"
  SSH_DIR: "{{.OUTPUT_DIR}}/ssh"

includes:
  tf:
    taskfile: ./terraform/Taskfile.yaml
    dir: ./terraform
