version: "3"

dotenv: [".env"]

vars:
  NAME: homelab
  ENV: prod
  TF: terraform # tofu
  TF_BACKEND_ENCRYPT: true
  TF_BACKEND_S3_BUCKET: "tf-solocuplabs-states"
  TF_BACKEND_S3_REGION: "us-east-1"
  OUTPUT_DIR: "{{.USER_WORKING_DIR}}/output"
  SSH_DIR: "{{.OUTPUT_DIR}}/ssh"

includes:
  infra:
    taskfile: ./infra/Taskfile.yaml
    dir: ./infra

  apps:
    taskfile: ./apps/Taskfile.yaml
    dir: ./apps
