version: "3"

vars:
  TF_BACKEND_S3_KEY: "infra/{{.ENV}}.tfstate"
  TF_BACKEND_ARGS: -backend-config="encrypt={{.TF_BACKEND_ENCRYPT}}" -backend-config="bucket={{.TF_BACKEND_S3_BUCKET}}" -backend-config="key={{.TF_BACKEND_S3_KEY}}" -backend-config="region={{.TF_BACKEND_S3_REGION}}"
  TFVAR_FILE: "{{.ENV}}.tfvars"

tasks:
  s3-backend:
    desc: "Create AWS S3 bucket for terraform backend"
    cmds:
      - |
        aws s3api list-buckets --query "Buckets[].Name" --output json | grep -q '"{{.TF_BACKEND_S3_BUCKET}}"' || \
        aws s3api create-bucket --bucket {{.TF_BACKEND_S3_BUCKET}} --region {{.TF_BACKEND_S3_REGION}} --endpoint-url https://s3.amazonaws.com
        aws s3api put-bucket-versioning --bucket {{.TF_BACKEND_S3_BUCKET}} --versioning-configuration Status=Enabled
        aws s3api put-bucket-tagging --bucket {{.TF_BACKEND_S3_BUCKET}} --tagging 'TagSet=[{Key=env,Value={{.ENV}}}]'
    silent: true
    internal: true

  init:
    deps: [s3-backend]
    desc: "Prepare your working directory for other commands"
    cmds:
      - |
        if [ -z "{{.module}}" ]; then
          {{.TF}} init {{.TF_BACKEND_ARGS}}
        else
          {{.TF}} -chdir=./modules/{{.module}} init
        fi
    silent: false
    vars:
      module: '{{.module | default ""}}'

  validate:
    desc: "Check whether the configuration is valid"
    cmds:
      - |
        if [ -z "{{.module}}" ]; then
          {{.TF}} validate
        else
          {{.TF}} validate -target=module.{{.module}}
        fi
    silent: true
    vars:
      module: '{{.module | default ""}}'

  plan:
    desc: "Show changes required by the current configuration"
    cmds:
      - |
        if [ -z "{{.module}}" ]; then
          {{.TF}} plan -var-file={{.TFVAR_FILE}}
        else
          {{.TF}} plan -target=module.{{.module}} -var-file={{.TFVAR_FILE}}
        fi
    silent: true
    vars:
      module: '{{.module | default ""}}'

  apply:
    desc: "Create or update infrastructure"
    cmds:
      - |
        if [ -z "{{.module}}" ]; then
          {{.TF}} apply -var-file={{.TFVAR_FILE}}
        else
          {{.TF}} apply -target=module.{{.module}} -var-file={{.TFVAR_FILE}}
        fi
    silent: true
    vars:
      module: '{{.module | default ""}}'

  destroy:
    desc: "Create or update infrastructure"
    cmds:
      - |
        if [ -z "{{.module}}" ]; then
          {{.TF}} destroy -var-file={{.TFVAR_FILE}}
        else
          {{.TF}} destroy -target=module.{{.module}} -var-file={{.TFVAR_FILE}}
        fi
    silent: true
    vars:
      module: '{{.module | default ""}}'

  format:
    desc: "Reformat your configuration in the standard style"
    cmds:
      - |
        {{.TF}} fmt -recursive .

  ssh:
    desc: "Generate SSH key and connect to specified node (vpn or dns)"
    vars:
      node: '{{.node | default ""}}'
      connect: "{{.connect | default false}}"
      ssh_key: "{{.SSH_DIR}}/{{.node}}.rsa"
    preconditions:
      - sh: '[ "{{.node}}" = "vpn" ] || [ "{{.node}}" = "dns" ]'
        msg: "invalid node '{{.node}}'; allowed values: 'vpn' or 'dns'"
      - sh: '{{.TF}} state list | grep -q "module.{{.node}}"'
        msg: "terraform state for node not found, apply configuration first"
    requires:
      vars:
        - node
    cmds:
      - |
        mkdir -p "{{.SSH_DIR}}"
        CREDENTIALS_KEY="{{.node}}_node_credentials"
        NODE_IP_KEY="{{.node}}_node_ip"
        {{.TF}} output -json "$CREDENTIALS_KEY" | jq -r .ssh_private_key > "{{.ssh_key}}"
        chmod 0600 "{{.ssh_key}}"
        if [ "{{.connect}}" == "true" ]; then
          USERNAME=$({{.TF}} output -json "$CREDENTIALS_KEY" | jq -r .username)
          IP_ADDR=$({{.TF}} output -json "$NODE_IP_KEY" | jq -r .)
          ssh-keygen -R "$IP_ADDR"
          ssh -i "{{.ssh_key}}" "$USERNAME@$IP_ADDR"
        fi
    silent: true
    generates:
      - "{{.ssh_key}}"

  kubeconfig:
    desc: "Generate 'kubeconfig'"
    vars:
      output_file: "{{.OUTPUT_DIR}}/kube/config"
      symlink: "{{.symlink | default false}}"
    preconditions:
      - sh: '{{.TF}} state list | grep -q "module.talos"'
        msg: "talos cluster is not deployed, apply configuration first"
    cmds:
      - |
        mkdir -p "$(dirname "{{.output_file}}")"
        {{.TF}} output -json | jq -r .talos_kubeconfig.value > {{.output_file}}
        if [ "{{.symlink}}" == "true" ]; then
          if [ ! -f "$HOME/.kube/config" ]; then
            mkdir -p "$HOME/.kube"
            ln -s "{{.output_file}}" "$HOME/.kube/config"
            echo "symlink created: $HOME/.kube/config -> {{.output_file}}"
          else
            echo "$HOME/.kube/config already exists, skipping symlink creation"
          fi
        fi
    silent: true
    generates:
      - "{{.output_file}}"

  kubeseal:
    desc: "Generate kubeseal cerificate"
    vars:
      output_file: "{{.OUTPUT_DIR}}/kubeseal/{{.NAME}}.cert"
    preconditions:
      - sh: '{{.TF}} state list | grep -q "module.talos"'
        msg: "talos cluster is not deployed, apply configuration first"
    cmds:
      - |
        mkdir -p "$(dirname "{{.output_file}}")"
        kubeseal --fetch-cert > {{.output_file}}
    silent: true
    generates:
      - "{{.output_file}}"

  talosconfig:
    desc: "Generate 'talosconfig'"
    vars:
      output_file: "{{.OUTPUT_DIR}}/talos/config"
      symlink: "{{.symlink | default false}}"
    preconditions:
      - sh: '{{.TF}} state list | grep -q "module.talos"'
        msg: "talos cluster is not deployed, apply configuration first"
    cmds:
      - |
        mkdir -p "$(dirname "{{.output_file}}")"
        {{.TF}} output -json | jq -r .talos_config.value > {{.output_file}}
        if [ "{{.symlink}}" == "true" ]; then
          if [ ! -f "$HOME/.talos/config" ]; then
            mkdir -p "$HOME/.talos"
            ln -s "{{.output_file}}" "$HOME/.talos/config"
            echo "symlink created: $HOME/.talos/config -> {{.output_file}}"
          else
            echo "$HOME/.talos/config already exists, skipping symlink creation"
          fi
        fi
    silent: true
    generates:
      - "{{.output_file}}"

  wireguard:
    desc: "Generate wireguard client configuration"
    vars:
      output_file: "{{.OUTPUT_DIR}}/wireguard/{{.NAME}}.conf"
    preconditions:
      - sh: '{{.TF}} state list | grep -q "module.vpn"'
        msg: "vpn instance is not deployed yet, apply configuration first"
    cmds:
      - |
        mkdir -p "$(dirname "{{.output_file}}")"
        {{.TF}} output --json wireguard_client_configuration | jq -r > {{.output_file}}
    silent: true
    generates:
      - "{{.output_file}}"
