version: "3"

vars:
  TF_BACKEND_ENCRYPT: true
  TF_BACKEND_S3_BUCKET: "tf-{{.NAME}}-{{.ENV}}-state"
  TF_BACKEND_S3_REGION: "us-east-1"
  TF_BACKEND_S3_KEY: "apps/{{.TF}}.tfstate"
  TF_BACKEND_ARGS: -backend-config="encrypt={{.TF_BACKEND_ENCRYPT}}" -backend-config="bucket={{.TF_BACKEND_S3_BUCKET}}" -backend-config="key={{.TF_BACKEND_S3_KEY}}" -backend-config="region={{.TF_BACKEND_S3_REGION}}"
  TFVAR_FILE: "{{.ENV}}.tfvars"

tasks:
  init:
    desc: "Prepare your working directory for other commands"
    cmds:
      - |
        if [ -z "{{.module}}" ]; then
          {{.TF}} init {{.TF_BACKEND_ARGS}}
        else
          {{.TF}} -chdir=./modules/{{.module}} init
        fi
    silent: true
    vars:
      module: '{{.module | default ""}}'

  validate:
    desc: "Check whether the configuration is valid"
    cmds:
      - |
        if [ -z "{{.module}}" ]; then
          {{.TF}} validate
        else
          {{.TF}} validate -target=module.{{.module}}
        fi
    silent: true
    vars:
      module: '{{.module | default ""}}'

  plan:
    desc: "Show changes required by the current configuration"
    cmds:
      - |
        if [ -z "{{.module}}" ]; then
          {{.TF}} plan -var-file={{.TFVAR_FILE}}
        else
          {{.TF}} plan -target=module.{{.module}} -var-file={{.TFVAR_FILE}}
        fi
    silent: true
    vars:
      module: '{{.module | default ""}}'

  apply:
    desc: "Create or update infrastructure"
    cmds:
      - |
        if [ -z "{{.module}}" ]; then
          {{.TF}} apply -var-file={{.TFVAR_FILE}}
        else
          {{.TF}} apply -target=module.{{.module}} -var-file={{.TFVAR_FILE}}
        fi
    silent: true
    vars:
      module: '{{.module | default ""}}'

  destroy:
    desc: "Create or update infrastructure"
    cmds:
      - |
        if [ -z "{{.module}}" ]; then
          {{.TF}} destroy -var-file={{.TFVAR_FILE}}
        else
          {{.TF}} destroy -target=module.{{.module}} -var-file={{.TFVAR_FILE}}
        fi
    silent: true
    vars:
      module: '{{.module | default ""}}'

  format:
    desc: "Reformat your configuration in the standard style"
    cmds:
      - |
        {{.TF}} fmt -recursive .
